[target.aarch64-unknown-linux-musl]
dockerfile = "./tools/cross/Dockerfile"

[target.arm-unknown-linux-musleabihf]
dockerfile = "./tools/cross/Dockerfile"

[target.armv7-unknown-linux-musleabihf]
dockerfile = "./tools/cross/Dockerfile"

[target.x86_64-unknown-linux-musl]
dockerfile = "./tools/cross/Dockerfile"

[target.x86_64-pc-windows-gnu]
dockerfile = "./tools/cross/Dockerfile"
