[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-gnu-gcc"
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-static"]

[env]
CC_x86_64_unknown_linux_musl = "x86_64-linux-gnu-gcc"
